services:
  db:
    image: postgres:18-alpine
    container_name: hack2cash-postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - hack2cash_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hack2cash-network


  backend:
    build:
      context: .
    container_name: hack2cash-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy # Attend que la DB soit prête avant de lancer l'app
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app # Montage pour le Hot-Reload (utile en développement)
    networks:
      - hack2cash-network


volumes:
  hack2cash_data:

networks:
  hack2cash-network:
    driver: bridge